# Generated by Django 4.0.5 on 2022-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_id', models.IntegerField()),
                ('Book_name', models.CharField(max_length=100)),
                ('Book_author', models.CharField(max_length=100)),
                ('Book_publish_year', models.DateField()),
                ('Book_price', models.FloatField()),
            ],
        ),
    ]
